package pojo;

// Generated 17-feb-2014 19:09:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AseguradoId generated by hbm2java
 */
@Embeddable
public class AseguradoId implements java.io.Serializable {

	private int codP;
	private boolean num;

	public AseguradoId() {
	}

	public AseguradoId(int codP, boolean num) {
		this.codP = codP;
		this.num = num;
	}

	@Column(name = "COD_P", nullable = false, precision = 5, scale = 0)
	public int getCodP() {
		return this.codP;
	}

	public void setCodP(int codP) {
		this.codP = codP;
	}

	@Column(name = "NUM", nullable = false, precision = 1, scale = 0)
	public boolean isNum() {
		return this.num;
	}

	public void setNum(boolean num) {
		this.num = num;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AseguradoId))
			return false;
		AseguradoId castOther = (AseguradoId) other;

		return (this.getCodP() == castOther.getCodP())
				&& (this.isNum() == castOther.isNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodP();
		result = 37 * result + (this.isNum() ? 1 : 0);
		return result;
	}

}
